# Generated by Django 5.2.1 on 2025-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='habilidades',
            field=models.TextField(blank=True, default='[]', max_length=500),
        ),
    ]
