# Generated by Django 5.2 on 2025-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='precio',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='arma',
            name='ammo',
            field=models.TextField(blank=True),
        ),
    ]
