# Generated by Django 5.2 on 2025-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demon', '0002_arma_precio_alter_arma_ammo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='ammo',
            new_name='ammoPrice',
        ),
        migrations.AlterField(
            model_name='arma',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
